const enMessage = {
  home: {
    survey: 'Survey',
    WHCTransactions: 'Wormhole Transactions',
    surveyTitle: 'Wormhole',
    surveyDes: 'Featured Property',
    latestAmount: 'Current Block',
    dayAmount: '24 Hours',
    allMount: 'All',
    blockTime: 'Block Time',
    height: 'Height',
    blockInfo: 'Block Information',
    recentBlock: {
      blockSize: 'Size(B)',
      blockHash: 'Block Hash'
    },
    latestBlock: 'Latest Blocks',
    burningDetails: 'Burning Details',
    progress: 'Progress',
    matureTime: 'Mature Time',
    address: 'Address',
    burningAmount: 'Amount (BCH)',
    burningWhcAmount: 'Amount（WHC）'
  },
  nav: {
    home: 'Home',
    block: 'Blocks',
    asset: 'Assets',
    wallet: 'Wallet',
    changeNet: 'Change Net',
    testNet: 'Test Net',
    mainNet: 'Main Net',
    changeLan: 'Change Language',
    enLan: 'English',
    zhLan: 'Chinese',
    search: 'Search address,hash or height',
    searchError: 'Your search did not match any records, please change the keywords and try again'
  },
  asset: {
    id: 'Property ID',
    name: 'Property Name',
    category: 'Category',
    subCategory: 'Sub Category',
    url: 'Url',
    address: ' Issuer Address',
    type: 'Property Type',
    smart: 'Smart Property',
    manage: 'Manage Property',
    crowd: 'Crowd Sale',
    isActive: 'Active',
    start: 'Start Time',
    end: 'End Time',
    alreadyBought: 'Already Bought',
    Ratio: 'Token / WHC',
    earlyBonus: 'Early Bonus',
    changeRecords: 'Changing Records',
    transferRecords: ' Transfer Records',
    owners: 'Owners',
    ownersAddress: 'Address',
    ownersAmount: 'Amount',
    ownersStatus: 'Status',
    blockTime: 'Block Time',
    Type: 'Type',
    txHash: 'Tx Hash',
    to: 'To',
    from: 'From',
    amount: 'Amount',
    oneAsset: 'Asset',
    searchHolder: 'Search asset id or asset name'
  },
  block: {
    blockExplorer: 'Block Explorer',
    details: 'Block Details',
    height: 'Height',
    strippedSize: 'Stripped Size(B)',
    comeOutTime: 'Time',
    whctransactionsNum: 'WHC Tx Count',
    transactions: 'Transactions',
    blockHash: 'Block Hash',
    confirmations: 'Confirmations',
    size: 'Size(B)',
    difficulty: 'Difficulty',
    nonce: 'Nonce',
    transactionsAll: 'Transactions Count',
    prevBlock: 'Prev Block',
    nextBlock: 'Next Block',
    merkleRoot: 'Merkle Root',
    transactionType: 'Transaction Type'
  },
  address: {
    details: 'Address Details',
    whcBalance: 'WHC Balance',
    whcExpense: 'Expense WHC Count',
    inputWhcCount: 'Input WHC Count',
    outputWhcCount: 'Output WHC Count',
    transactionHistory: 'Transactions History'
  },
  burn: {
    burnExplorer: 'Burning Explorer',
    availWhcCount: 'Available WHC Count',
    burnInfo: 'Buring Details',
    process: 'Burning Process',
    estimatedTime: 'Estimated Mature Time'
  },
  common: {
    to: 'to',
    startTime: 'Start Time',
    endTime: 'End Time',
    crowd: 'Crowd Sale',
    precision: 'Precision',
    issuer: 'Issuer',
    amount: 'Amount',
    back: 'Go Back',
    propertyDetails: 'Property Details',
    more: 'more',
    basic: 'Basic Information',
    address: 'Address',
    time: 'Time',
    count: 'Count',
    whcTransactionList: 'Wormhole Transaction List',
    txhash: 'txhash',
    showMore: 'Show More',
    type: 'Type',
    state: 'State',
    valid: 'valid',
    invalid: 'invalid',
    fees: 'Fees',
    showAllAddress: 'Show All Address',
    feeRate: 'FeeRate',
    feerate: 'fee rate',
    minFeeRate: 'Min Fee Rate',
    avgFeeRate: 'Avg Fee Rate',
    maxFeeRate: 'Max Fee Rate',
    assetsList: 'Assets List',
    balance: 'Balance'
  },
  tx: {
    details: 'Transaction Details',
    confimationState: 'Confirmation State',
    rawData: 'Raw Data'
  }
}

export default enMessage
