const zhMessage = {
  home: {
    survey: '概况',
    WHCTransactions: '虫洞交易数量',
    surveyTitle: 'Wormhole',
    surveyDes: 'Featured Property',
    latestAmount: '当前区块',
    dayAmount: '24小时',
    allMount: '全部',
    blockTime: '时间',
    height: '区块高度',
    blockInfo: '区块信息',
    recentBlock: {
      blockSize: '块体积(B)',
      blockHash: '块哈希'
    },
    latestBlock: '最新出块',
    burningDetails: '燃烧信息',
    progress: '燃烧进度',
    matureTime: '成熟时间',
    address: '地址',
    burningAmount: '数量 (BCH)',
    burningWhcAmount: '数量（WHC）'
  },
  nav: {
    home: '首页',
    block: '区块浏览',
    asset: '资产浏览',
    wallet: '我的钱包',
    changeNet: '网关切换',
    testNet: '测试网',
    mainNet: '主网',
    changeLan: '语言切换',
    enLan: '英语',
    zhLan: '中文',
    search: '地址、高度或哈希',
    searchError: '未找到符合查询的数据，请更换关键词后重试'
  },
  asset: {
    id: '资产ID',
    name: '资产名称',
    category: '一级分类',
    subCategory: '二级分类',
    url: 'Url',
    address: '发行者地址',
    type: '资产类型',
    smart: '固定资产',
    manage: '可管理资产',
    crowd: '众筹',
    isActive: '是否活跃',
    start: '开始时间',
    end: '结束时间',
    alreadyBought: '已买数量',
    Ratio: 'WHC兑换比率',
    earlyBonus: '早鸟奖励',
    changeRecords: '资产变更记录',
    transferRecords: '转账记录',
    owners: '持有者列表',
    ownersAddress: '地址',
    ownersAmount: '数量',
    ownersStatus: '状态',
    blockTime: '时间',
    Type: '交易类型',
    txHash: '交易哈希',
    to: '转入地址',
    from: '转出地址',
    amount: '交易数量',
    oneAsset: '资产',
    searchHolder: '资产名称或资产id'
  },
  block: {
    blockExplorer: '区块浏览',
    details: '区块详情',
    height: '区块高度',
    strippedSize: 'Stripped Size(B)',
    comeOutTime: '时间',
    whctransactionsNum: 'WHC交易数量',
    transactions: '交易数量',
    blockHash: '块哈希',
    confirmations: '确认数量',
    size: '块体积(B)',
    difficulty: '难度',
    nonce: 'Nonce',
    transactionsAll: '交易数量',
    prevBlock: '前序区块',
    nextBlock: '后序区块',
    merkleRoot: '默克尔树根',
    transactionType: '交易类型'
  },
  address: {
    details: '地址详情',
    whcBalance: 'WHC余额',
    whcExpense: '消耗 WHC 数量',
    inputWhcCount: '转入 WHC 数量',
    outputWhcCount: '转出 WHC 数量',
    transactionHistory: '交易历史'
  },
  burn: {
    burnExplorer: '燃烧浏览',
    availWhcCount: '可用WHC数量',
    burnInfo: '燃烧',
    process: '燃烧进度',
    estimatedTime: '预计成熟时间'
  },
  common: {
    to: 'to',
    startTime: '开始时间',
    endTime: '结束时间',
    crowd: '众筹',
    precision: '精度',
    issuer: '发行者地址',
    amount: '数量',
    back: '返回',
    propertyDetails: '资产详情',
    more: '更多',
    basic: '基础信息',
    address: '地址',
    time: '时间',
    count: 'Count',
    whcTransactionList: '虫洞交易列表',
    txhash: '交易哈希',
    showMore: '查看更多',
    type: '类型',
    state: '状态',
    valid: '有效',
    invalid: '无效',
    fees: '费用',
    showAllAddress: '查看所有地址',
    feeRate: '费率',
    feerate: '费率',
    minFeeRate: '最低费率',
    avgFeeRate: '平均费率',
    maxFeeRate: '最高费率',
    assetsList: '资产列表',
    balance: '余额'
  },
  tx: {
    details: '交易详情',
    confimationState: '确认状态',
    rawData: '原始数据',
    query: '交易查询'
  }
}

export default zhMessage
